### ISSUE TITLE
TOML catalog definition error

### ISSUE THREAD

**Issue by GibsonRuitiari** [c0de-wizard/stargazer#21]
Gradle build fails due to invalid definition of entries in the toml catalog. 
You have defined detekt and spotless twice thus the error.

**Comment by c0de-wizard** [comment]
Hi @GibsonRuitiari, thanks for reporting this. The error is due to a conflict of the word `plugins` which is also used by AS. I have created a fix for this in this [PR](https://github.com/c0de-wizard/stargazer/pull/22).
